name: flutter_testing_methods
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Add the following dependencies
  go_router: ^14.0.2
  provider: ^6.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.2
  # Add the following dependencies
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # For testing, when the app relies on web services or APIs
  mockito: ^5.4.5
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
